### ISSUE TITLE
Font Switcher unknown in settings.json

### ISSUE THREAD

**Issue by antpowell** [evan-buss/font-switcher#10]
For some reason `"font-switcher.enableLivePreview": true,` now shows as Unknown Configuration Setting in settings.json. 

I have uninstalled and reinstalled to see if there was a mistake picking up the package settings but still the same issue. 

![image](https://user-images.githubusercontent.com/10569986/114595818-69bb4a80-9c54-11eb-9246-cbcd848d955d.png)

![image](https://user-images.githubusercontent.com/10569986/114595873-7d66b100-9c54-11eb-9d16-41d89a77abbe.png)

**Comment by evan-buss** [comment]
Hi, I recently released v4.0 and got rid of the `font-switcher.enableLivePreview` configuration setting. The live preview is now on by default and you no longer need to have a separate `font-switcher.fontFamily` configuration setting. It will now use the standard `editor.fontFamily` setting.

Here is a [list of the v4.0 changes](https://github.com/evan-buss/font-switcher/blob/master/CHANGELOG.md#400).

Sorry for the confusion!

**Comment by antpowell** [comment]
Perfect!! Thanks for the quick response and I will checkout the v4 notes!!!
